$ koji build koji-test justjavac-0.1-1.fc22.src.rpm
Uploading srpm: justjavac-0.1-1.fc22.src.rpm
[====================================] 100% 00:00:00   6.44 KiB 141.64 KiB/sec
Created task: 21285
Task info: http://10.1.60.111/koji/taskinfo?taskID=21285
Watching tasks (this may be safely interrupted)...
21285 build (koji-test, justjavac-0.1-1.fc22.src.rpm): free
21285 build (koji-test, justjavac-0.1-1.fc22.src.rpm): free -> open (kojibuilder1)
21285 build (koji-test, justjavac-0.1-1.fc22.src.rpm): open (kojibuilder1) -> FAILED:
Fault: <Fault 1: 'Traceback (most recent call last):\n
File "/usr/lib/python2.7/site-packages/koji/daemon.py", line 1161, in runTask\n
response = (handler.run(),)\n
File "/usr/lib/python2.7/site-packages/koji/tasks.py", line 158, in run\n
return koji.util.call_with_argcheck(self.handler, self.params, self.opts)\n
File "/usr/lib/python2.7/site-packages/koji/util.py", line 154, in call_with_argcheck\n
return func(*args, **kwargs)\n
File "/usr/sbin/kojid", line 832, in handler\n
h = self.readSRPMHeader(srpm)\n
File "/usr/sbin/kojid", line 905, in readSRPMHeader\n
fo = koji.openRemoteFile(relpath, **opts)\n
File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 1431, in openRemoteFile\n
src = urllib2.urlopen(url)\n
File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen\n
return opener.open(url, data, timeout)\n
File "/usr/lib64/python2.7/urllib2.py", line 437, in open\n
response = meth(req, response)\n
File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response\n
\'http\', request, response, code, msg, hdrs)\n
File "/usr/lib64/python2.7/urllib2.py", line 475, in error\n
return self._call_chain(*args)\n
File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain\n
result = func(*args)\n
File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default\n
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)\n
HTTPError: HTTP Error 403: Forbidden\n'>
  0 free  0 open  0 done  1 failed
